Repository ember-elements/ember-elements, pull requests merged in 2021-07, with the labels that each got.

#339 Configure github actions
  .github/workflows/Core-quality.yml
  .github/workflows/EE-Core-quality.yml
  .github/workflows/EE-Core-tests.yml
  .github/workflows/Icons-quality.yml
  .stylelintrc.json
  packages/core/.stylelintrc.json
  packages/core/addon/components/_examples.scss
  packages/core/addon/components/forms/control-group/_control-group.scss
  packages/core/addon/components/forms/file-input/_file-input.scss
  packages/core/addon/components/forms/input-group/_input-group.scss
  packages/core/addon/components/html-table/_html-table.scss
  packages/core/app/styles/core.scss
  packages/core/package.json
  packages/core/tsconfig.json
  packages/icons/package.json
  yarn.lock
Labels: CI

#344 [core] add ember compatibility check to CI
  .github/workflows/Core-quality.yml
  packages/core/addon/components/overlay/index.hbs
  packages/core/addon/components/overlay/index.ts
  packages/core/package.json
  yarn.lock
Labels: CI

#345 [core] Remove all computed props and use tracked props
  .gitignore
  packages/core/.eslintignore
  packages/core/.gitignore
  packages/core/addon/components/button-group/index.ts
  packages/core/addon/components/button/index.hbs
  packages/core/addon/components/button/index.ts
  packages/core/addon/components/callout/index.ts
  packages/core/addon/components/card/index.hbs
  packages/core/addon/components/card/index.ts
  packages/core/addon/components/collapse/index.ts
  packages/core/addon/components/dialog/index.ts
  packages/core/addon/components/divider/index.ts
  packages/core/addon/components/drawer/index.ts
  packages/core/addon/components/forms/checkbox/index.ts
  packages/core/addon/components/forms/control-group/index.ts
  packages/core/addon/components/forms/controls.ts
  packages/core/addon/components/forms/file-input/index.ts
  packages/core/addon/components/forms/form-group/index.ts
  packages/core/addon/components/forms/input-group/index.hbs
  packages/core/addon/components/forms/input-group/index.ts
  packages/core/addon/components/forms/numeric-input/index.ts
  packages/core/addon/components/forms/radio-group/index.hbs
  packages/core/addon/components/forms/radio-group/index.ts
  packages/core/addon/components/forms/radio/index.ts
  packages/core/addon/components/forms/switch/index.ts
  packages/core/addon/components/forms/text-area/index.ts
  packages/core/addon/components/html-select/index.ts
  packages/core/addon/components/html-table/index.ts
  packages/core/addon/components/icon/index.ts
  packages/core/addon/components/navbar/index.ts
  packages/core/addon/components/navbar/navbar-divider/index.ts
  packages/core/addon/components/navbar/navbar-group/index.ts
  packages/core/addon/components/navbar/navbar-heading/index.ts
  packages/core/addon/components/overlay/index.ts
  packages/core/addon/components/popover/index.ts
  packages/core/addon/components/progress-bar/index.ts
  packages/core/addon/components/select/index.ts
  packages/core/addon/components/select/multi-select/index.ts
  packages/core/addon/components/spinner/index.ts
  packages/core/addon/components/tag-input/index.ts
  packages/core/addon/components/tag/index.ts
  packages/core/addon/components/tooltip/index.ts
  packages/core/tests/dummy/app/components/comp-test.hbs
  packages/core/tests/dummy/app/components/comp-test.ts
  packages/core/tests/dummy/app/templates/application.hbs
  packages/icons/.gitignore
Labels: Type: maintenance

#356 [core] resolve overlay animation
  packages/core/addon/components/overlay/index.ts
  packages/core/app/styles/common.scss
  packages/core/app/styles/core.scss
  packages/core/tests/dummy/app/styles/app.scss
Labels: Core, Type: bug
